resources:
  aws_elasticache_replication_group:
    header: ElastiCache clusters
    attributes:
      - id
      - primary_endpoint_address
      - reader_endpoint_address
      - member_clusters
  aws_db_instance:
    header: RDS databases
    attributes:
      - address
  aws_rds_cluster:
    header: Aurora clusters
    attributes:
      - cluster_identifier
      - endpoint
      - reader_endpoint
      - engine
  aws_sqs_queue:
    header: SQS Queues
    attributes:
      - url
      - id
  aws_s3_bucket:
    header: S3 buckets
    attributes: []
  aws_iam_role:
    header: IAM role
    attributes:
      - arn
  aws_iam_user:
    header: IAM user
    attributes:
      - id
      - arn
  kubernetes_service_account:
    header: Service Account
    attributes:
      - id
  aws_ecr_repository:
    header: ECR repository
    attributes:
      - repository_url
      - image_tag_mutability
  aws_sns_topic:
    header: SNS topic
    attributes:
      - name
  aws_cloudfront_distribution:
    header: Cloudfront
    attributes:
      - id
      - aliases
  kubernetes_secret:
    header: Secrets
    attributes:
      - id
  kubernetes_config_map:
    header: Config map
    attributes:
      - id
  mongodbatlas_cluster:
    header: MongoDB Atlas cluster
    attributes:
      - name
      - mongo_uri_with_options
  aws_dynamodb_table:
    header: DynamoDB table
    attributes:
      - id
      - arn
  aws_wafv2_web_acl:
    header: WAF
    attributes:
      - name
      - arn
  aws_msk_cluster:
    header: MSK cluster
    attributes:
      - cluster_name
      - arn
      - bootstrap_brokers_tls
  aws_cloudwatch_log_group:
    header: Cloudwatch log group
    attributes:
      - name
      - arn
  aws_lambda_function:
    header: Lambda function
    attributes:
      - function_name
      - arn
  aws_elasticsearch_domain:
    header: Elasticsearch domain
    attributes:
      - domain_name
      - endpoint
      - kibana_endpoint
